export { default as sSlider } from './s-slider'
export { default as sNews } from './s-news'
export { default as sRegist } from './s-regist'
export { default as sLesson } from './s-lesson'
export { default as sFriendShip } from './s-friend-ship'
export { default as sTeacher } from './s-teacher'